<?php

namespace Mfonte\HteCli\Services;

use Carbon\Carbon;
use Mfonte\HteCli\Contracts\ApacheManagerInterface;
use Mfonte\HteCli\Contracts\FilesystemInterface;

/**
 * Manages Apache VirtualHost configurations for HTE-CLI.
 *
 * Reads, writes, and manipulates Apache config files under sites-available/sites-enabled.
 * All filesystem access goes through FilesystemInterface for testability.
 */
class ApacheManager implements ApacheManagerInterface
{
    /** @var FilesystemInterface */
    private $fs;

    /** @var string */
    private $sitesAvailableDir;

    /** @var string */
    private $sitesEnabledDir;

    /** @var string */
    private $certsDir;

    /**
     * @param FilesystemInterface $fs
     * @param string $sitesAvailableDir
     * @param string $sitesEnabledDir
     * @param string $certsDir
     */
    public function __construct(
        FilesystemInterface $fs,
        $sitesAvailableDir = '/etc/apache2/sites-available',
        $sitesEnabledDir = '/etc/apache2/sites-enabled',
        $certsDir = '/etc/apache2/certs-selfsigned'
    ) {
        $this->fs = $fs;
        $this->sitesAvailableDir = $sitesAvailableDir;
        $this->sitesEnabledDir = $sitesEnabledDir;
        $this->certsDir = $certsDir;
    }

    /**
     * {@inheritdoc}
     */
    public function getVhostsList()
    {
        $virtualHosts = [];
        $configFiles = $this->fs->findByExtension($this->sitesAvailableDir, 'conf');

        foreach ($configFiles as $file) {
            $configFile = basename($file);
            $contents = $this->fs->getContents($file);

            if ($contents === false) {
                continue;
            }

            // Only process configs generated by HTE-CLI
            if (
                strpos($contents, '# Auto-generated by the test environment creator') === false &&
                strpos($contents, '# Auto-generated by HTE-Cli') === false
            ) {
                continue;
            }

            // Extract PHP-FPM version and domain from the proxy handler
            $phpver = $domain = null;
            if (preg_match('/SetHandler "proxy:unix:\/var\/run\/php\/php([0-9\.]+)-fpm-([^"\|]+)/', $contents, $matches)) {
                $phpver = $matches[1];
                $domain = str_replace('.sock', '', $matches[2]);
            }

            // Detect SSL by matching <VirtualHost 127.0.0.1:443>
            $ssl = false;
            $sslCertFile = $sslKeyFile = null;
            if (preg_match('/<VirtualHost 127\.0\.0\.1:443>/', $contents)) {
                $ssl = true;
                if (preg_match('/SSLCertificateFile "([^"]+)"/', $contents, $matches)) {
                    $sslCertFile = $matches[1];
                }
                if (preg_match('/SSLCertificateKeyFile "([^"]+)"/', $contents, $matches)) {
                    $sslKeyFile = $matches[1];
                }
            }

            // Detect Force HTTPS
            $forceSsl = strpos($contents, '# Auto-generated Force HTTPS') !== false;

            // Check if enabled (file exists in sites-enabled)
            $enabled = $this->fs->fileExists($this->sitesEnabledDir . "/{$configFile}");

            // Extract index from filename (e.g., 002-domain.conf)
            $index = 0;
            if (preg_match('/^([0-9]+)-(.*)\.conf$/ui', $configFile, $matches)) {
                $index = intval($matches[1]);
            }

            // Extract document root
            $documentRoot = null;
            if (preg_match('/DocumentRoot ([^\n]+)/', $contents, $matches)) {
                $documentRoot = $matches[1];
            }

            $virtualHosts[] = [
                'index' => $index,
                'conf' => $file,
                'name' => $configFile,
                'phpver' => $phpver,
                'domain' => $domain,
                'docroot' => $documentRoot,
                'enabled' => $enabled,
                'ssl' => $ssl,
                'forcedssl' => $forceSsl,
                'sslcertfile' => $sslCertFile,
                'sslkeyfile' => $sslKeyFile,
            ];
        }

        // Sort by index ascending
        usort($virtualHosts, function ($a, $b) {
            return $a['index'] <=> $b['index'];
        });

        return $virtualHosts;
    }

    /**
     * {@inheritdoc}
     */
    public function getConfByDomain(string $domain)
    {
        $vhosts = $this->getVhostsList();

        foreach ($vhosts as $vhost) {
            if ($vhost['domain'] === $domain) {
                return $vhost;
            }
        }

        return null;
    }

    /**
     * {@inheritdoc}
     */
    public function getConfMaxIndex()
    {
        $files = $this->fs->findByExtension($this->sitesAvailableDir, 'conf');
        $maxIndex = 0;

        foreach ($files as $file) {
            $filename = basename($file);
            if (preg_match('/^([0-9]+).*\.conf$/ui', $filename, $matches)) {
                $index = intval($matches[1]);
                if ($index >= $maxIndex) {
                    $maxIndex = $index;
                }
            }
        }

        return str_pad($maxIndex + 1, 3, '0', STR_PAD_LEFT);
    }

    /**
     * {@inheritdoc}
     */
    public function createVhost(string $domain, string $documentRoot, string $phpVersion, bool $enableHttps = true, bool $forceHttps = true)
    {
        $conf = $this->getConf($domain, $documentRoot, $phpVersion, $enableHttps, $forceHttps);
        $maxIndex = $this->getConfMaxIndex();
        $confFile = $this->sitesAvailableDir . "/{$maxIndex}-{$domain}.conf";

        $result = $this->fs->putContents($confFile, $conf);
        if ($result !== false && $this->fs->fileExists($confFile)) {
            return $confFile;
        }

        return null;
    }

    /**
     * {@inheritdoc}
     */
    public function normalizeIndexes()
    {
        $result = ['renamed' => 0, 'errors' => []];
        $vhosts = $this->getVhostsList();

        if (empty($vhosts)) {
            return $result;
        }

        // Already sorted by index from getVhostsList()
        $newIndex = 1;
        foreach ($vhosts as $vhost) {
            $expectedIndex = str_pad($newIndex, 3, '0', STR_PAD_LEFT);
            $currentIndex = str_pad($vhost['index'], 3, '0', STR_PAD_LEFT);

            if ($currentIndex !== $expectedIndex) {
                $oldName = $vhost['name'];
                $newName = "{$expectedIndex}-{$vhost['domain']}.conf";

                $oldPath = $this->sitesAvailableDir . "/{$oldName}";
                $newPath = $this->sitesAvailableDir . "/{$newName}";

                $wasEnabled = $vhost['enabled'];
                $enabledOldPath = $this->sitesEnabledDir . "/{$oldName}";
                $enabledNewPath = $this->sitesEnabledDir . "/{$newName}";

                if ($this->fs->rename($oldPath, $newPath)) {
                    $result['renamed']++;

                    // Update symlink in sites-enabled if the site was enabled
                    if ($wasEnabled && $this->fs->isLink($enabledOldPath)) {
                        $this->fs->delete($enabledOldPath);
                        $this->fs->symlink($newPath, $enabledNewPath);
                    }
                } else {
                    $result['errors'][] = "Failed to rename {$oldName} to {$newName}";
                }
            }

            $newIndex++;
        }

        return $result;
    }

    /**
     * {@inheritdoc}
     */
    public function needsLocalhostBypassFix(string $confFile)
    {
        if (!$this->fs->fileExists($confFile)) {
            return false;
        }

        $contents = $this->fs->getContents($confFile);
        if ($contents === false) {
            return false;
        }

        // No Force HTTPS at all
        if (strpos($contents, '# Auto-generated Force HTTPS') === false) {
            return false;
        }

        // Already properly fixed
        if (strpos($contents, '# Auto-generated Force HTTPS (bypassed for localhost requests)') !== false) {
            // Check for broken formatting (empty lines between directives)
            if (preg_match('/RewriteCond\s+%\{HTTPS\}\s+off\s*\n\s*\n/m', $contents)) {
                return true; // Needs re-fixing
            }
            return false;
        }

        // Old-style Force HTTPS without localhost bypass
        if (preg_match('/RewriteCond\s+%\{HTTPS\}\s+off\s*\n\s*RewriteRule/m', $contents)) {
            return true;
        }

        return false;
    }

    /**
     * {@inheritdoc}
     */
    public function fixLocalhostBypass(string $confFile)
    {
        if (!$this->fs->fileExists($confFile)) {
            return ['success' => false, 'error' => 'File not found'];
        }

        if (!$this->fs->isWritable($confFile)) {
            return ['success' => false, 'error' => 'File not writable'];
        }

        $contents = $this->fs->getContents($confFile);
        $originalContents = $contents;
        $matched = false;

        // Pattern 1: Broken new format (empty lines between directives)
        $brokenNewPattern = '/^([^\S\n]*)(# Auto-generated Force HTTPS \(bypassed for localhost requests\))\s*\n+\s*RewriteEngine On\s*\n+\s*RewriteCond %\{HTTPS\} off\s*\n+\s*RewriteCond %\{REMOTE_ADDR\} !\^127\\\\\.0\\\\\.0\\\\\.1\$\s*\n+\s*RewriteCond %\{REMOTE_ADDR\} !\^::1\$\s*\n+\s*RewriteRule \^\/(.*?) https:\/\/%\{HTTP_HOST\}%\{REQUEST_URI\} \[R=301,L\]/m';

        if (preg_match($brokenNewPattern, $contents, $matches)) {
            $indent = $matches[1];
            $matched = true;

            $newBlock = $indent . "# Auto-generated Force HTTPS (bypassed for localhost requests)\n" .
                        $indent . "RewriteEngine On\n" .
                        $indent . "RewriteCond %{HTTPS} off\n" .
                        $indent . "RewriteCond %{REMOTE_ADDR} !^127\\.0\\.0\\.1\$\n" .
                        $indent . "RewriteCond %{REMOTE_ADDR} !^::1\$\n" .
                        $indent . "RewriteRule ^/(.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]";

            $contents = preg_replace($brokenNewPattern, $newBlock, $contents, 1);
        }

        // Pattern 2: Old format (without localhost bypass)
        if (!$matched) {
            $oldPattern = '/^([^\S\n]*)(# Auto-generated Force HTTPS)\s*\n\s*RewriteEngine On\s*\n\s*RewriteCond %\{HTTPS\} off\s*\n\s*RewriteRule \^\/(.*?) https:\/\/%\{HTTP_HOST\}%\{REQUEST_URI\} \[R=301,L\]/m';

            if (preg_match($oldPattern, $contents, $matches)) {
                $indent = $matches[1];
                $matched = true;

                $newBlock = $indent . "# Auto-generated Force HTTPS (bypassed for localhost requests)\n" .
                            $indent . "RewriteEngine On\n" .
                            $indent . "RewriteCond %{HTTPS} off\n" .
                            $indent . "RewriteCond %{REMOTE_ADDR} !^127\\.0\\.0\\.1\$\n" .
                            $indent . "RewriteCond %{REMOTE_ADDR} !^::1\$\n" .
                            $indent . "RewriteRule ^/(.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]";

                $contents = preg_replace($oldPattern, $newBlock, $contents, 1);
            }
        }

        if (!$matched) {
            return ['success' => false, 'error' => 'Could not find Force HTTPS pattern to fix'];
        }

        if ($contents === $originalContents) {
            return ['success' => false, 'error' => 'No changes needed or pattern not matched'];
        }

        if ($this->fs->putContents($confFile, $contents) === false) {
            return ['success' => false, 'error' => 'Failed to write file'];
        }

        return ['success' => true, 'error' => null];
    }

    /**
     * {@inheritdoc}
     */
    public function hasHtaccessHttpsRedirect(string $docroot)
    {
        $htaccessPath = rtrim($docroot, '/') . '/.htaccess';

        if (!$this->fs->fileExists($htaccessPath)) {
            return ['has_redirect' => false, 'file' => null, 'line' => null];
        }

        $contents = $this->fs->getContents($htaccessPath);
        if ($contents === false) {
            return ['has_redirect' => false, 'file' => null, 'line' => null];
        }

        $pattern = '/RewriteCond\s+.*(%{HTTPS}|%{SERVER_PORT}|HTTP_X_FORWARDED_PROTO).*(off|!=on|80|http).*?\n\s*RewriteRule.*https:\/\//is';

        if (preg_match($pattern, $contents, $matches, PREG_OFFSET_CAPTURE)) {
            $offset = $matches[0][1];
            $line = substr_count(substr($contents, 0, $offset), "\n") + 1;

            return [
                'has_redirect' => true,
                'file' => $htaccessPath,
                'line' => $line,
            ];
        }

        return ['has_redirect' => false, 'file' => null, 'line' => null];
    }

    /**
     * {@inheritdoc}
     */
    public function getConf(string $domain, string $documentRoot, string $phpVersion, bool $enableHttps = true, bool $forceHttps = true)
    {
        $newline = "\\n";
        $date = Carbon::now()->format('Y-m-d H:i:s');
        $certsDir = $this->certsDir;

        $conf_autorewrite = <<<CONF
    # Auto-generated Force HTTPS (bypassed for localhost requests)
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteCond %{REMOTE_ADDR} !^127\.0\.0\.1$
    RewriteCond %{REMOTE_ADDR} !^::1$
    RewriteRule ^/(.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
    CONF;

        $conf_http = <<<CONF
<VirtualHost 127.0.0.1:80>
    # Auto-generated by HTE-Cli on $date
    ServerName $domain
    ServerAlias www.$domain
    DocumentRoot $documentRoot
    ServerAdmin admin@localhost.net
    UseCanonicalName Off
    Options -ExecCGI -Includes
    RemoveHandler cgi-script .cgi .pl .plx .ppl .perl
    CustomLog \${APACHE_LOG_DIR}/$domain combined
    CustomLog \${APACHE_LOG_DIR}/$domain-bytes_log "%{%s}t %I .$newline%{%s}t %O ."

    # Enable HTTP2
    Protocols h2 http/1.1

    <FilesMatch \.php$>
        # Apache 2.4.10+ can proxy to unix socket
        SetHandler "proxy:unix:/var/run/php/php$phpVersion-fpm-$domain.sock|fcgi://localhost/"
    </FilesMatch>

    <IfModule mod_brotli.c>
        AddOutputFilterByType BROTLI_COMPRESS text/html text/plain text/xml text/css text/javascript application/x-javascript application/javascript application/json application/x-font-ttf application/vnd.ms-fontobject image/x-icon
    </IfModule>

    <Directory $documentRoot/>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        order allow,deny
        allow from all
        Require all granted
    </Directory>

##AUTOREWRITE##
</VirtualHost>

CONF;

        $conf_https = <<<CONF
<IfModule mod_ssl.c>
    <VirtualHost 127.0.0.1:443>
        # Auto-generated by HTE-Cli on $date
        ServerName $domain
        ServerAlias www.$domain
        DocumentRoot $documentRoot
        ServerAdmin admin@localhost.net
        UseCanonicalName Off
        Options -ExecCGI -Includes
        RemoveHandler cgi-script .cgi .pl .plx .ppl .perl
        CustomLog \${APACHE_LOG_DIR}/ssl-$domain combined
        CustomLog \${APACHE_LOG_DIR}/ssl-$domain-bytes_log "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"

        # Enable HTTP2
        Protocols h2 http/1.1

        <FilesMatch "\.(cgi|shtml|phtml|php)$">
            SSLOptions +StdEnvVars
        </FilesMatch>

        <Directory $documentRoot/>
            Options -Indexes +FollowSymLinks
            AllowOverride All
            order allow,deny
            allow from all
            Require all granted
        </Directory>

        <IfModule mod_brotli.c>
            AddOutputFilterByType BROTLI_COMPRESS text/html text/plain text/xml text/css text/javascript application/x-javascript application/javascript application/json application/x-font-ttf application/vnd.ms-fontobject image/x-icon
        </IfModule>

        <FilesMatch \.php$>
            # Apache 2.4.10+ can proxy to unix socket
            SetHandler "proxy:unix:/var/run/php/php$phpVersion-fpm-$domain.sock|fcgi://localhost/"
        </FilesMatch>

        SSLEngine on
        SSLCipherSuite ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP
        SSLCertificateFile "$certsDir/$domain.crt"
        SSLCertificateKeyFile "$certsDir/$domain.key"
    </VirtualHost>
</IfModule>

CONF;

        if ($enableHttps) {
            if ($forceHttps) {
                $conf_http = str_replace('##AUTOREWRITE##', $conf_autorewrite, $conf_http);
            } else {
                $conf_http = str_replace('##AUTOREWRITE##', '', $conf_http);
            }

            return implode(PHP_EOL, [$conf_http, $conf_https]);
        }

        return str_replace('##AUTOREWRITE##', '', $conf_http);
    }
}
