<?php

namespace Tests\Unit;

use Tests\TestCase;
use Tests\Doubles\InMemoryFilesystem;
use Mfonte\HteCli\Services\ApacheManager;

/**
 * Tests for ApacheManager service class.
 *
 * All filesystem operations use InMemoryFilesystem to keep tests fast
 * and fully isolated from the real filesystem.
 *
 * Config generation tests (getConf) are pure string tests and do not
 * require any filesystem state. Filesystem-dependent tests pre-populate
 * InMemoryFilesystem with realistic Apache config content.
 */
class ApacheManagerTest extends TestCase
{
    /** @var InMemoryFilesystem */
    private $fs;

    /** @var ApacheManager */
    private $apache;

    protected function setUp(): void
    {
        parent::setUp();

        $this->fs = new InMemoryFilesystem([], [
            '/test/sites-available',
            '/test/sites-enabled',
            '/test/certs',
        ]);

        $this->apache = new ApacheManager(
            $this->fs,
            '/test/sites-available',
            '/test/sites-enabled',
            '/test/certs'
        );
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /**
     * Build a minimal but realistic HTE-CLI Apache config string.
     *
     * @param string $domain
     * @param string $docroot
     * @param string $phpVersion
     * @param bool   $ssl
     * @param bool   $forceHttps
     * @return string
     */
    private function buildHteConf($domain, $docroot, $phpVersion, $ssl = false, $forceHttps = false)
    {
        $marker = '# Auto-generated by HTE-Cli on 2025-01-01 00:00:00';
        $handler = 'SetHandler "proxy:unix:/var/run/php/php' . $phpVersion . '-fpm-' . $domain . '.sock|fcgi://localhost/"';
        $forceBlock = $forceHttps
            ? "    # Auto-generated Force HTTPS\n    RewriteEngine On\n    RewriteCond %{HTTPS} off\n    RewriteRule ^/(.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]"
            : '';

        $conf = <<<CONF
<VirtualHost 127.0.0.1:80>
    {$marker}
    ServerName {$domain}
    ServerAlias www.{$domain}
    DocumentRoot {$docroot}
    ServerAdmin admin@localhost.net

    <FilesMatch \.php$>
        {$handler}
    </FilesMatch>

{$forceBlock}
</VirtualHost>

CONF;

        if ($ssl) {
            $conf .= <<<CONF
<IfModule mod_ssl.c>
    <VirtualHost 127.0.0.1:443>
        {$marker}
        ServerName {$domain}
        DocumentRoot {$docroot}

        <FilesMatch \.php$>
            {$handler}
        </FilesMatch>

        SSLEngine on
        SSLCertificateFile "/test/certs/{$domain}.crt"
        SSLCertificateKeyFile "/test/certs/{$domain}.key"
    </VirtualHost>
</IfModule>

CONF;
        }

        return $conf;
    }

    // -------------------------------------------------------------------------
    // Config generation tests — pure string, no filesystem state required
    // -------------------------------------------------------------------------

    /**
     * @test
     */
    public function testGetConfGeneratesValidHttpConfig()
    {
        $conf = $this->apache->getConf('example.test', '/var/www/html', '8.4', false, false);

        $this->assertStringContainsString('<VirtualHost 127.0.0.1:80>', $conf);
        $this->assertStringContainsString('ServerName example.test', $conf);
        $this->assertStringContainsString('ServerAlias www.example.test', $conf);
        $this->assertStringContainsString('DocumentRoot /var/www/html', $conf);
        $this->assertStringContainsString('php8.4-fpm-example.test.sock', $conf);
        $this->assertStringContainsString('Protocols h2 http/1.1', $conf);
        $this->assertStringNotContainsString('<VirtualHost 127.0.0.1:443>', $conf);
        $this->assertStringNotContainsString('SSLEngine', $conf);
    }

    /**
     * @test
     */
    public function testGetConfGeneratesHttpsConfig()
    {
        $conf = $this->apache->getConf('secure.test', '/var/www/secure', '8.3', true, false);

        $this->assertStringContainsString('<VirtualHost 127.0.0.1:80>', $conf);
        $this->assertStringContainsString('<VirtualHost 127.0.0.1:443>', $conf);
        $this->assertStringContainsString('SSLEngine on', $conf);
        // Certs must point to the custom test certs dir
        $this->assertStringContainsString('SSLCertificateFile "/test/certs/secure.test.crt"', $conf);
        $this->assertStringContainsString('SSLCertificateKeyFile "/test/certs/secure.test.key"', $conf);
        // No force-HTTPS rewrite in HTTP vhost
        $this->assertStringNotContainsString('RewriteEngine On', $conf);
    }

    /**
     * @test
     */
    public function testGetConfGeneratesForceHttpsConfig()
    {
        $conf = $this->apache->getConf('forced.test', '/var/www/forced', '8.2', true, true);

        $this->assertStringContainsString('# Auto-generated Force HTTPS', $conf);
        $this->assertStringContainsString('RewriteEngine On', $conf);
        $this->assertStringContainsString('RewriteCond %{HTTPS} off', $conf);
        $this->assertStringContainsString('RewriteRule', $conf);
        // Both VHosts must be present
        $this->assertStringContainsString('<VirtualHost 127.0.0.1:80>', $conf);
        $this->assertStringContainsString('<VirtualHost 127.0.0.1:443>', $conf);
    }

    /**
     * @test
     */
    public function testGetConfIncludesSecurityDirectives()
    {
        $conf = $this->apache->getConf('test.local', '/var/www', '8.4', false, false);

        $this->assertStringContainsString('Options -ExecCGI -Includes', $conf);
        $this->assertStringContainsString('RemoveHandler cgi-script .cgi .pl .plx .ppl .perl', $conf);
        $this->assertStringContainsString('Options -Indexes +FollowSymLinks', $conf);
        $this->assertStringContainsString('AllowOverride All', $conf);
    }

    /**
     * @test
     */
    public function testGetConfIncludesBrotliCompression()
    {
        $conf = $this->apache->getConf('test.local', '/var/www', '8.4', false, false);

        $this->assertStringContainsString('<IfModule mod_brotli.c>', $conf);
        $this->assertStringContainsString('AddOutputFilterByType BROTLI_COMPRESS', $conf);
    }

    /**
     * @test
     */
    public function testGetConfIncludesPhpFpmHandler()
    {
        $conf = $this->apache->getConf('phpapp.test', '/var/www/app', '7.4', false, false);

        $this->assertStringContainsString('<FilesMatch \.php$>', $conf);
        $this->assertStringContainsString(
            'SetHandler "proxy:unix:/var/run/php/php7.4-fpm-phpapp.test.sock|fcgi://localhost/"',
            $conf
        );
    }

    /**
     * @test
     */
    public function testGetConfIncludesAutoGeneratedMarker()
    {
        $conf = $this->apache->getConf('marked.test', '/var/www', '8.4', false, false);

        $this->assertStringContainsString('# Auto-generated by HTE-Cli', $conf);
    }

    /**
     * @test
     */
    public function testGetConfIncludesCustomLogging()
    {
        $conf = $this->apache->getConf('logged.test', '/var/www', '8.4', true, false);

        $this->assertStringContainsString('CustomLog ${APACHE_LOG_DIR}/logged.test combined', $conf);
        $this->assertStringContainsString('CustomLog ${APACHE_LOG_DIR}/ssl-logged.test combined', $conf);
    }

    /**
     * @test
     */
    public function testLocalhostBypassInForceHttps()
    {
        $conf = $this->apache->getConf('bypass.test', '/var/www', '8.4', true, true);

        $this->assertStringContainsString('RewriteCond %{REMOTE_ADDR} !^127\\.0\\.0\\.1$', $conf);
        $this->assertStringContainsString('RewriteCond %{REMOTE_ADDR} !^::1$', $conf);
    }

    // -------------------------------------------------------------------------
    // Filesystem-dependent tests
    // -------------------------------------------------------------------------

    /**
     * @test
     */
    public function testGetConfMaxIndex()
    {
        $this->fs->putContents('/test/sites-available/001-alpha.conf', 'dummy');
        $this->fs->putContents('/test/sites-available/002-beta.conf', 'dummy');

        $result = $this->apache->getConfMaxIndex();

        $this->assertSame('003', $result);
    }

    /**
     * @test
     */
    public function testGetConfMaxIndexWithNoFiles()
    {
        // No files pre-populated — directory is empty
        $result = $this->apache->getConfMaxIndex();

        $this->assertSame('001', $result);
    }

    /**
     * @test
     */
    public function testCreateVhost()
    {
        $confFile = $this->apache->createVhost('new.test', '/var/www/new', '8.1', true, false);

        $this->assertNotNull($confFile);
        $this->assertStringContainsString('/test/sites-available/', $confFile);
        $this->assertStringContainsString('new.test', $confFile);

        // File must actually exist in the in-memory filesystem
        $this->assertTrue($this->fs->fileExists($confFile));

        $content = $this->fs->getContents($confFile);
        $this->assertStringContainsString('ServerName new.test', $content);
        $this->assertStringContainsString('# Auto-generated by HTE-Cli', $content);
        $this->assertStringContainsString('php8.1-fpm-new.test.sock', $content);
    }

    /**
     * @test
     */
    public function testGetVhostsList()
    {
        $this->fs->putContents(
            '/test/sites-available/001-example.test.conf',
            $this->buildHteConf('example.test', '/var/www/example', '8.2', false, false)
        );
        $this->fs->putContents(
            '/test/sites-available/002-secure.test.conf',
            $this->buildHteConf('secure.test', '/var/www/secure', '8.3', true, false)
        );

        $list = $this->apache->getVhostsList();

        $this->assertCount(2, $list);

        $first = $list[0];
        $this->assertSame(1, $first['index']);
        $this->assertSame('example.test', $first['domain']);
        $this->assertSame('8.2', $first['phpver']);
        $this->assertSame('/var/www/example', $first['docroot']);
        $this->assertFalse($first['ssl']);
        $this->assertFalse($first['forcedssl']);
        $this->assertFalse($first['enabled']);

        $second = $list[1];
        $this->assertSame(2, $second['index']);
        $this->assertSame('secure.test', $second['domain']);
        $this->assertTrue($second['ssl']);
        $this->assertFalse($second['forcedssl']);
    }

    /**
     * @test
     */
    public function testGetVhostsListIgnoresNonHteConfigs()
    {
        // Non-HTE config (no HTE marker)
        $this->fs->putContents(
            '/test/sites-available/000-default.conf',
            "<VirtualHost *:80>\n    ServerName default\n</VirtualHost>\n"
        );
        // Genuine HTE config
        $this->fs->putContents(
            '/test/sites-available/001-myapp.test.conf',
            $this->buildHteConf('myapp.test', '/var/www/myapp', '8.4', false, false)
        );

        $list = $this->apache->getVhostsList();

        $this->assertCount(1, $list);
        $this->assertSame('myapp.test', $list[0]['domain']);
    }

    /**
     * @test
     */
    public function testGetConfByDomain()
    {
        $this->fs->putContents(
            '/test/sites-available/001-alpha.test.conf',
            $this->buildHteConf('alpha.test', '/var/www/alpha', '8.1', false, false)
        );
        $this->fs->putContents(
            '/test/sites-available/002-beta.test.conf',
            $this->buildHteConf('beta.test', '/var/www/beta', '8.2', false, false)
        );

        $vhost = $this->apache->getConfByDomain('beta.test');

        $this->assertNotNull($vhost);
        $this->assertSame('beta.test', $vhost['domain']);
        $this->assertSame('8.2', $vhost['phpver']);
    }

    /**
     * @test
     */
    public function testGetConfByDomainReturnsNullWhenNotFound()
    {
        $this->fs->putContents(
            '/test/sites-available/001-only.test.conf',
            $this->buildHteConf('only.test', '/var/www/only', '8.0', false, false)
        );

        $result = $this->apache->getConfByDomain('missing.test');

        $this->assertNull($result);
    }

    /**
     * @test
     */
    public function testNormalizeIndexes()
    {
        // Gaps: 001, 003, 005
        $this->fs->putContents(
            '/test/sites-available/001-first.test.conf',
            $this->buildHteConf('first.test', '/var/www/first', '8.0', false, false)
        );
        $this->fs->putContents(
            '/test/sites-available/003-third.test.conf',
            $this->buildHteConf('third.test', '/var/www/third', '8.1', false, false)
        );
        $this->fs->putContents(
            '/test/sites-available/005-fifth.test.conf',
            $this->buildHteConf('fifth.test', '/var/www/fifth', '8.2', false, false)
        );

        $result = $this->apache->normalizeIndexes();

        $this->assertSame(2, $result['renamed']);
        $this->assertEmpty($result['errors']);

        // Renamed files must exist; original gap filenames must be gone
        $this->assertTrue($this->fs->fileExists('/test/sites-available/002-third.test.conf'));
        $this->assertTrue($this->fs->fileExists('/test/sites-available/003-fifth.test.conf'));
        $this->assertFalse($this->fs->fileExists('/test/sites-available/003-third.test.conf'));
        $this->assertFalse($this->fs->fileExists('/test/sites-available/005-fifth.test.conf'));
    }

    /**
     * @test
     */
    public function testNormalizeIndexesNoGaps()
    {
        // Sequential — no renames expected
        $this->fs->putContents(
            '/test/sites-available/001-a.test.conf',
            $this->buildHteConf('a.test', '/var/www/a', '8.0', false, false)
        );
        $this->fs->putContents(
            '/test/sites-available/002-b.test.conf',
            $this->buildHteConf('b.test', '/var/www/b', '8.1', false, false)
        );
        $this->fs->putContents(
            '/test/sites-available/003-c.test.conf',
            $this->buildHteConf('c.test', '/var/www/c', '8.2', false, false)
        );

        $result = $this->apache->normalizeIndexes();

        $this->assertSame(0, $result['renamed']);
        $this->assertEmpty($result['errors']);
    }

    /**
     * @test
     */
    public function testNormalizeIndexesUpdatesSymlinks()
    {
        // 001 is enabled (symlink in sites-enabled), 003 has a gap and is also enabled
        $this->fs->putContents(
            '/test/sites-available/001-a.test.conf',
            $this->buildHteConf('a.test', '/var/www/a', '8.0', false, false)
        );
        $this->fs->putContents(
            '/test/sites-available/003-b.test.conf',
            $this->buildHteConf('b.test', '/var/www/b', '8.1', false, false)
        );

        // Simulate enabled site via symlink
        $this->fs->symlink(
            '/test/sites-available/003-b.test.conf',
            '/test/sites-enabled/003-b.test.conf'
        );

        $result = $this->apache->normalizeIndexes();

        $this->assertSame(1, $result['renamed']);

        // Old symlink must be gone; new symlink must point at the renamed file
        $this->assertFalse($this->fs->isLink('/test/sites-enabled/003-b.test.conf'));
        $this->assertTrue($this->fs->isLink('/test/sites-enabled/002-b.test.conf'));

        $links = $this->fs->getLinks();
        $this->assertSame('/test/sites-available/002-b.test.conf', $links['/test/sites-enabled/002-b.test.conf']);
    }

    // -------------------------------------------------------------------------
    // needsLocalhostBypassFix tests
    // -------------------------------------------------------------------------

    /**
     * @test
     */
    public function testNeedsLocalhostBypassFixDetectsOldConfig()
    {
        $oldConfig = <<<CONF
<VirtualHost 127.0.0.1:80>
    # Auto-generated by HTE-Cli on 2024-01-01
    ServerName old.test
    DocumentRoot /var/www/old

    # Auto-generated Force HTTPS
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^/(.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</VirtualHost>
CONF;

        $path = '/test/sites-available/001-old.test.conf';
        $this->fs->putContents($path, $oldConfig);

        $this->assertTrue($this->apache->needsLocalhostBypassFix($path));
    }

    /**
     * @test
     */
    public function testNeedsLocalhostBypassFixReturnsFalseForNewConfig()
    {
        $newConfig = <<<CONF
<VirtualHost 127.0.0.1:80>
    # Auto-generated by HTE-Cli on 2024-01-01
    ServerName new.test
    DocumentRoot /var/www/new

    # Auto-generated Force HTTPS (bypassed for localhost requests)
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteCond %{REMOTE_ADDR} !^127\.0\.0\.1$
    RewriteCond %{REMOTE_ADDR} !^::1$
    RewriteRule ^/(.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</VirtualHost>
CONF;

        $path = '/test/sites-available/001-new.test.conf';
        $this->fs->putContents($path, $newConfig);

        $this->assertFalse($this->apache->needsLocalhostBypassFix($path));
    }

    /**
     * @test
     */
    public function testNeedsLocalhostBypassFixReturnsFalseForNoForceHttps()
    {
        $noForceConfig = <<<CONF
<VirtualHost 127.0.0.1:80>
    # Auto-generated by HTE-Cli on 2024-01-01
    ServerName noforce.test
    DocumentRoot /var/www/noforce
</VirtualHost>
CONF;

        $path = '/test/sites-available/001-noforce.test.conf';
        $this->fs->putContents($path, $noForceConfig);

        $this->assertFalse($this->apache->needsLocalhostBypassFix($path));
    }

    /**
     * @test
     */
    public function testNeedsLocalhostBypassFixReturnsFalseForNonexistentFile()
    {
        $this->assertFalse($this->apache->needsLocalhostBypassFix('/test/sites-available/ghost.conf'));
    }

    /**
     * @test
     */
    public function testNeedsLocalhostBypassFixDetectsBrokenFormat()
    {
        // New marker present, but empty lines between directives
        $brokenConfig = <<<CONF
<VirtualHost 127.0.0.1:80>
    # Auto-generated by HTE-Cli on 2024-01-01
    ServerName broken.test
    DocumentRoot /var/www/broken

    # Auto-generated Force HTTPS (bypassed for localhost requests)


    RewriteEngine On


    RewriteCond %{HTTPS} off


    RewriteCond %{REMOTE_ADDR} !^127\.0\.0\.1$


    RewriteCond %{REMOTE_ADDR} !^::1$


    RewriteRule ^/(.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</VirtualHost>
CONF;

        $path = '/test/sites-available/001-broken.test.conf';
        $this->fs->putContents($path, $brokenConfig);

        $this->assertTrue($this->apache->needsLocalhostBypassFix($path));
    }

    // -------------------------------------------------------------------------
    // fixLocalhostBypass tests
    // -------------------------------------------------------------------------

    /**
     * @test
     */
    public function testFixLocalhostBypassUpdatesOldConfig()
    {
        $oldConfig = <<<CONF
<VirtualHost 127.0.0.1:80>
    # Auto-generated by HTE-Cli on 2024-01-01
    ServerName old.test
    DocumentRoot /var/www/old

    # Auto-generated Force HTTPS
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^/(.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</VirtualHost>
CONF;

        $path = '/test/sites-available/001-old.test.conf';
        $this->fs->putContents($path, $oldConfig);

        $result = $this->apache->fixLocalhostBypass($path);

        $this->assertTrue($result['success']);
        $this->assertNull($result['error']);

        $newContent = $this->fs->getContents($path);
        $this->assertStringContainsString(
            '# Auto-generated Force HTTPS (bypassed for localhost requests)',
            $newContent
        );
        $this->assertStringContainsString('RewriteCond %{REMOTE_ADDR} !^127\\.0\\.0\\.1$', $newContent);
        $this->assertStringContainsString('RewriteCond %{REMOTE_ADDR} !^::1$', $newContent);
    }

    /**
     * @test
     */
    public function testFixLocalhostBypassFixesBrokenFormat()
    {
        $brokenConfig = <<<CONF
<VirtualHost 127.0.0.1:80>
    # Auto-generated by HTE-Cli on 2024-01-01
    ServerName broken.test
    DocumentRoot /var/www/broken

    # Auto-generated Force HTTPS (bypassed for localhost requests)


    RewriteEngine On


    RewriteCond %{HTTPS} off


    RewriteCond %{REMOTE_ADDR} !^127\.0\.0\.1$


    RewriteCond %{REMOTE_ADDR} !^::1$


    RewriteRule ^/(.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</VirtualHost>
CONF;

        $path = '/test/sites-available/001-broken.test.conf';
        $this->fs->putContents($path, $brokenConfig);

        $result = $this->apache->fixLocalhostBypass($path);

        $this->assertTrue($result['success']);

        $newContent = $this->fs->getContents($path);
        // After fixing, RewriteCond lines must follow each other without empty lines
        $this->assertStringContainsString(
            "RewriteCond %{HTTPS} off\n    RewriteCond %{REMOTE_ADDR}",
            $newContent
        );
        $this->assertStringNotContainsString("RewriteCond %{HTTPS} off\n\n", $newContent);
    }

    /**
     * @test
     */
    public function testFixLocalhostBypassFailsForNonexistentFile()
    {
        $result = $this->apache->fixLocalhostBypass('/test/sites-available/ghost.conf');

        $this->assertFalse($result['success']);
        $this->assertSame('File not found', $result['error']);
    }

    /**
     * @test
     */
    public function testFixLocalhostBypassPreservesOtherConfig()
    {
        $oldConfig = <<<CONF
<VirtualHost 127.0.0.1:80>
    # Auto-generated by HTE-Cli on 2024-01-01
    ServerName test.local
    ServerAlias www.test.local
    DocumentRoot /var/www/test
    ServerAdmin admin@localhost.net

    <FilesMatch \.php$>
        SetHandler "proxy:unix:/var/run/php/php8.4-fpm-test.local.sock|fcgi://localhost/"
    </FilesMatch>

    <Directory /var/www/test/>
        Options -Indexes +FollowSymLinks
        AllowOverride All
    </Directory>

    # Auto-generated Force HTTPS
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^/(.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</VirtualHost>
CONF;

        $path = '/test/sites-available/001-test.local.conf';
        $this->fs->putContents($path, $oldConfig);

        $result = $this->apache->fixLocalhostBypass($path);

        $this->assertTrue($result['success']);

        $newContent = $this->fs->getContents($path);

        // Other config sections must be intact
        $this->assertStringContainsString('ServerName test.local', $newContent);
        $this->assertStringContainsString('ServerAlias www.test.local', $newContent);
        $this->assertStringContainsString('DocumentRoot /var/www/test', $newContent);
        $this->assertStringContainsString('php8.4-fpm-test.local.sock', $newContent);
        $this->assertStringContainsString('Options -Indexes +FollowSymLinks', $newContent);

        // Fix must be applied
        $this->assertStringContainsString(
            '# Auto-generated Force HTTPS (bypassed for localhost requests)',
            $newContent
        );
    }

    // -------------------------------------------------------------------------
    // hasHtaccessHttpsRedirect tests
    // -------------------------------------------------------------------------

    /**
     * @test
     */
    public function testHasHtaccessHttpsRedirectDetectsRedirect()
    {
        $htaccess = <<<HTACCESS
RewriteEngine On

# Redirect to https
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
HTACCESS;

        $docroot = '/var/www/myapp';
        $this->fs->putContents($docroot . '/.htaccess', $htaccess);

        $result = $this->apache->hasHtaccessHttpsRedirect($docroot);

        $this->assertTrue($result['has_redirect']);
        $this->assertSame($docroot . '/.htaccess', $result['file']);
        $this->assertIsInt($result['line']);
        $this->assertGreaterThan(0, $result['line']);
    }

    /**
     * @test
     */
    public function testHasHtaccessHttpsRedirectReturnsFalseForNoRedirect()
    {
        $htaccess = <<<HTACCESS
RewriteEngine On

# Non-HTTPS rewrite rules
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php [L]
HTACCESS;

        $docroot = '/var/www/myapp';
        $this->fs->putContents($docroot . '/.htaccess', $htaccess);

        $result = $this->apache->hasHtaccessHttpsRedirect($docroot);

        $this->assertFalse($result['has_redirect']);
        $this->assertNull($result['file']);
        $this->assertNull($result['line']);
    }

    /**
     * @test
     */
    public function testHasHtaccessHttpsRedirectReturnsFalseForNoHtaccess()
    {
        // No .htaccess file put into InMemoryFilesystem
        $result = $this->apache->hasHtaccessHttpsRedirect('/var/www/empty');

        $this->assertFalse($result['has_redirect']);
        $this->assertNull($result['file']);
        $this->assertNull($result['line']);
    }

    /**
     * @test
     */
    public function testHasHtaccessHttpsRedirectDetectsAlternatePattern()
    {
        $htaccess = <<<HTACCESS
RewriteEngine On

# Alternative HTTPS redirect pattern
RewriteCond %{HTTPS} !=on
RewriteRule ^(.*)$ https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]
HTACCESS;

        $docroot = '/var/www/altapp';
        $this->fs->putContents($docroot . '/.htaccess', $htaccess);

        $result = $this->apache->hasHtaccessHttpsRedirect($docroot);

        $this->assertTrue($result['has_redirect']);
        $this->assertSame($docroot . '/.htaccess', $result['file']);
    }
}
